### PR TITLE
Added a JSON schema for IDE-friendly creation of threat models

### PR DESCRIPTION
**Pull request by adedayo**
Congratulations once again!

As promised in the previous PR. Please find a follow-on PR with a JSON schema for IDE-friendly creation of Open Threat Models.

Kind regards,
Dayo

### CODE REVIEW

**Comment by dfernandezvigo** [comment]
Hi Adelayo,
thanks for your contributions and interest on Open Threat Model.
The OTM JSON schema that we are using is inside Startleft project at https://github.com/iriusrisk/startleft/blob/main/startleft/resources/schemas/otm_schema.json
Let me suggest you to take a look at it.
Your are probably right. We'll move the existing file to this OpenThreatModel repository.
Thank you

**Comment by adedayo** [comment]
Thanks @dfernandezvigo.

If you moved the existing file from startleft into this repository I could contribute to that as there are improvements that I believe could be made to it too!

Kind regards,
Dayo

**Comment by Ogglas** [comment]
@dfernandezvigo Correct URL: https://github.com/iriusrisk/startleft/blob/main/otm/resources/schemas/otm_schema.json. It would be great if the schema was added here.

**Comment by daFont-iriusrisk** [comment]
Good morning @adedayo  finally we moved the schema into this repository in this PR #15 so this PR will be closed.

Thank you again for your collaboration.

**Comment by adedayo** [comment]
Excellent! Thank you so much!

**Pull request closed without merging**
